# Generated by Django 5.0.3 on 2024-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=100)),
                ('destination_ip', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('payload', models.TextField()),
            ],
        ),
    ]
